----1.1
--SELECT MADA, MA_NVIEN, CAST(THOIGIAN AS DECIMAL(10,2)) AS ThoiGian_ThapPhan
--FROM PHANCONG;

--SELECT MADA, MA_NVIEN, CONVERT(DECIMAL(10,2), THOIGIAN) AS ThoiGian_ThapPhan
--FROM PHANCONG;

----1.2 Kết quả kiểu decimal(10,2)
--SELECT DA.TENDEAN, 
--       CAST(SUM(PC.THOIGIAN) AS DECIMAL(10,2)) AS TongGio
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;


--SELECT DA.TENDEAN, 
--       CONVERT(DECIMAL(10,2), SUM(PC.THOIGIAN)) AS TongGio
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;


----Kết quả kiểu varchar
--SELECT DA.TENDEAN, 
--       CAST(SUM(PC.THOIGIAN) AS VARCHAR(50)) AS TongGioChuoi
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;


--SELECT DA.TENDEAN, 
--       CONVERT(VARCHAR(50), SUM(PC.THOIGIAN)) AS TongGioChuoi
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;

----1.3

--SELECT PB.TENPHG, 
--       CAST(AVG(NV.LUONG) AS DECIMAL(10,2)) AS LuongTB
--FROM NHANVIEN NV
--JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
--GROUP BY PB.TENPHG;


--SELECT PB.TENPHG, 
--       CONVERT(DECIMAL(10,2), AVG(NV.LUONG)) AS LuongTB
--FROM NHANVIEN NV
--JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
--GROUP BY PB.TENPHG;


--SELECT PB.TENPHG, 
--       FORMAT(AVG(NV.LUONG), '#,###.00') AS LuongTB_DinhDang
--FROM NHANVIEN NV
--JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
--GROUP BY PB.TENPHG;

---- BAI 2
--SELECT DA.TENDEAN, 
--       CEILING(SUM(PC.THOIGIAN)) AS TongGio_Ceiling
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;

--SELECT DA.TENDEAN, 
--       FLOOR(SUM(PC.THOIGIAN)) AS TongGio_Floor
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;

--SELECT DA.TENDEAN, 
--       ROUND(SUM(PC.THOIGIAN), 2) AS TongGio_Round2So
--FROM PHANCONG PC
--JOIN DEAN DA ON PC.MADA = DA.MADA
--GROUP BY DA.TENDEAN;


--DECLARE @LuongTB DECIMAL(10,2);


--SELECT @LuongTB = ROUND(AVG(LUONG), 2)
--FROM NHANVIEN NV
--JOIN PHONGBAN PB ON NV.PHG = PB.MAPHG
--WHERE PB.TENPHG = N'Nghiên cứu';


--SELECT HONV, TENLOT, TENNV, LUONG
--FROM NHANVIEN NV
--WHERE LUONG > @LuongTB;
-- BAI3
--CREATE FUNCTION LAYTENDUONG(@DCHI NVARCHAR(50))
--RETURNS NVARCHAR(50)
--BEGIN
--DECLARE @VITRI INT
--DECLARE @CHIEUDAI INT
--SET @VITRI=CHARINDEX(' ',@DCHI)+1
--SET @CHIEUDAI=CHARINDEX(',',@DCHI)-@VITRI
--RETURN (SUBSTRING(@DCHI,@VITRI,@CHIEUDAI))
--END

--CREATE FUNCTION TenNV_KT2HOA(@tenNV NVARCHAR(15))
--RETURNS NVARCHAR(15)
--BEGIN
--	RETURN (LOWER(LEFT(@TENNV,1))+UPPER(SUBSTRING(@TENNV,2,1))
--			+LOWER(RIGHT(@TENNV,LEN(@TENNV)-2)))
--		END

--SELECT 
--    UPPER(NV.HONV) AS HONV,
--    LOWER(NV.TENLOT) AS TENLOT,
--    dbo.TenNV_KT2HOA(NV.TENNV) AS TENNV,
--    dbo.LAYTENDUONG(NV.DCHI) AS TENDUONG
--,COUNT(MANV) AS SOTHANNHAN
--FROM NHANVIEN , THANNHAN
--WHERE MANV=MA_NVIEN
--GROUP BY HONV,TENLOT,TENNV,DCHI
--HAVING COUNT(MANV)>=2

--bai 4
SELECT *
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;

SELECT 
    MANV, HONV, TENLOT, TENNV,
    DATEDIFF(YEAR, NGSINH, GETDATE()) 
        - CASE 
            WHEN MONTH(NGSINH) > MONTH(GETDATE()) 
              OR (MONTH(NGSINH) = MONTH(GETDATE()) AND DAY(NGSINH) > DAY(GETDATE()))
            THEN 1 ELSE 0 
          END AS TUOI
FROM NHANVIEN;
SELECT 
    MANV, HONV, TENLOT, TENNV, NGSINH,
    DATENAME(WEEKDAY, NGSINH) AS THU_SINH
FROM NHANVIEN;
SELECT 
    PB.TENPHG,
    CONCAT(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV) AS TruongPhong,
    PB.NG_NHANCHUC,
    FORMAT(PB.NG_NHANCHUC, 'dd-MM-yy') AS NGAY_NHAN_CHUC_FORMAT
FROM PHONGBAN PB
JOIN NHANVIEN NV ON PB.TRPHG = NV.MANV;











